---
title: "TransPhylo show and tell demo"
author: "Zoe A. Dyson"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  prettydoc::html_pretty:
    theme: cayman
    number_sections: TRUE
    fig_width: 11
    fig_height: 15
---

## Set up knitr
```{r setup}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE) 
```

## Import required packages
```{r import_packages}

# Reporting
library(knitr)
library(prettydoc)

# Wrangling
library(tidyverse)
library(lubridate)
library(coda)

# Phylo
library(TransPhylo)
library(ape)
library(treeio)

```

## Document versions
```{r log_verions}

# R
sessionInfo()$R.version$version.string

# Packages
# Reporting
packageVersion("knitr")
packageVersion("prettydoc")

# Wrangling
packageVersion("tidyverse")
packageVersion("lubridate")
packageVersion("coda")

# Phylo
packageVersion("TransPhylo")
packageVersion("ape")
packageVersion("treeio")

# Plotting
packageVersion("ggplot2")

```

## Initialise environment
```{r init_env}

# Set seed
set.seed(3551)

# set working directory
setwd("~/Dropbox/Presentations/Holt_lab_meetings/21022022_Show_and_tell_TransPhylo")

```


## Import data
```{r import_data}

# Import beast tree
tree <-read.beast("BEAST.tre")

```


## Plot dated tree
```{r plot_dated_phylo}

# remove multifurcations
tree <- multi2di(tree@phylo)

# make sure all branch lengths are at least 1 day
tree$edge.length <- pmax(tree$edge.length,1/365) 

# Plot dated tree calibdated with last sample date
ptree<-TransPhylo::ptreeFromPhylo(tree,dateLastSample=decimal_date(ymd("2019-08-09")))
plot(ptree, show.tip.label = F)

```


## Set model parameters
```{r set_model_params}

# Set params
# Convert generation time to gamma distribution i.e. Shape = mean^2/sd^2, Scale = sd^2/mean
w.shape<- ((1/12)^2)/((0.5/12)^2) # Gamma distribution in years (to match tree)
w.scale <- ((0.5/12)^2)/(1/12) # Gamma distribution in years (to match tree)
w.mean <- 1/12 # Gamma distribution in years (to match tree)
w.sd <- 0.5/12 # Gamma distribution in years (to match tree)
dateT<-decimal_date(ymd("2019-08-10")) + 30/365 # one month later than last sample
chain_length <- 1e5

```


## Run MCMC 
```{r run_mcmc}

# Run MCMC chain
mcmc_res<-inferTTree(ptree,
                     mcmcIterations=chain_length,
                     w.mean = w.mean,
                     w.std = w.sd,
                     dateT=dateT,
                     verbose=F)

```


## Check MCMC convergence
```{r check_convergence_mcmc}

# Plot MCMC traces
plot(mcmc_res)

```


## Check ESS >100, preferably >200
```{r check_ess}
# Convert to coda format & get ESS
mcmc_coda<-convertToCoda(mcmc_res)
effectiveSize(mcmc_coda)

```


## Plot results
```{r plot_results}

# Get most representative (aka medoid) tree & plot
mediod_tree<-medTTree(mcmc_res)
plot(mediod_tree)


# Get transmission tree from medoid tre & plot
transmisssion_tree<-extractTTree(mediod_tree)
plot(transmisssion_tree,type='detailed',w.shape,w.scale)

# Compute transmisson matrix (probability of direct transmission for all pairs of individuals)
transmission_mat<-computeMatWIW(mcmc_res)
lattice::levelplot(transmission_mat,xlab='',ylab='')

# Compute transmission matrix (for each pairs of individuals 
# how many intermediates there are in the transmission chain)
transmission_dist_mat<-computeMatTDist(mcmc_res)
lattice::levelplot(transmission_dist_mat,xlab='',ylab='')

# Plot unsampled cases
unsampled_cases <- getIncidentCases(mcmc_res,show.plot = T)

# Plot realised generation times
gen_tme_dist <- getGenerationTimeDist(mcmc_res,show.plot = T)

# Plot sampling times
samp_time_dist <- getSamplingTimeDist(mcmc_res,show.plot = T)

# Duration of infection times for specific individuals
inf_time <- getInfectionTimeDist(mcmc_res,
                     k=c('32639_1_104@5_to_15@2016.934','32639_1_105@5_to_15@2016.956'),
                     show.plot = T)


# Offspeing distribution
off_dist <- getOffspringDist(mcmc_res,
                 k=c('32639_1_104@5_to_15@2016.934','32639_1_105@5_to_15@2016.956'),
                 show.plot = T) 

```
